### ISSUE TITLE
When installed via jspm, the line in config.js is not correct

### ISSUE THREAD

**Issue by gregoryagu** [charlespockert/aurelia-debugger#1]
I just installed via jspm.

It entered this in config.js:

```
"charlespockert/aurelia-debugger": "github:charlespockert/aurelia-debugger@master",
```

It should be this:

```
"aurelia-debugger": "github:charlespockert/aurelia-debugger@master",
```

**Comment by charlespockert** [comment]
@gregoryagu I've updated the readme to correct the error: you can install using an alias

`jspm install aurelia-debugger=github:charlespockert/aurelia-debugger`

and then register using `.plugin('aurelia-debugger');`

or you can install as per the README and register using `.plugin('charlespockert/aurelia-debugger');`

Thanks for the catch though :)
